language: r

warnings_are_errors: true
cache: packages

r_binary_packages:
  - testthat
  - Rcpp

r_packages:
  - covr
  
r_github_packages:
  - KlausVigo/ape    

after_success:
  - Rscript -e 'library(covr); coveralls()'
