// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// RNCL
Rcpp::List RNCL(SEXP params, SEXP paramsVecR);
RcppExport SEXP _rncl_RNCL(SEXP paramsSEXP, SEXP paramsVecRSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type paramsVecR(paramsVecRSEXP);
    rcpp_result_gen = Rcpp::wrap(RNCL(params, paramsVecR));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP rncl_collapse_single_cpp(SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP rncl_n_singletons(SEXP);
RcppExport SEXP rncl_RNCL(SEXP, SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_rncl_RNCL", (DL_FUNC) &_rncl_RNCL, 2},
    {"rncl_collapse_single_cpp", (DL_FUNC) &rncl_collapse_single_cpp, 4},
    {"rncl_n_singletons",        (DL_FUNC) &rncl_n_singletons,        1},
    {"rncl_RNCL",                (DL_FUNC) &rncl_RNCL,                2},
    {NULL, NULL, 0}
};

RcppExport void R_init_rncl(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
